swagger: "2.0"

info:
  version: 1.0.0
  title: bot-lax-adaptor api
  description: a web interface to interacting with lax via the bot-lax-adaptor

schemes:
  - https

host: lax.elifesciences.org:8080
basePath: /
paths:
  /xml:
    post:
      description: upload an xml file
      responses:
        2000:
          description: the remote name of the uploaded xml file

  /xml/{filename}/generate:
    post:
      description: generate article-json from an uploaded xml file
      parameters:
        - name: filename
          in: path
          type: string
          required: true
          description: name of remote xml file
      responses:
        200:
          description: the remote name of the generated article-json file

  /ajson/{filename}/validate:
    post:
      description: validate generated article-json
      parameters:
        - name: filename
          in: path
          type: string
          required: true
          description: name of remote article-json file
      responses:
        200:
          description: success or failure details of the validation attempt
